language: node_js

# os: osx
# osx_image: xcode11

branches:
  only:
    - master
    - develop

cache:
  npm: true
  cocoapods: true
  podfile: template/ios/Podfile
  directories:
    - node_modules
    - template/node_modules
    - template/ios/Pods

node_js:
  - 12

install:
  # - gem install cocoapods
  - yarn install
  - (cd template && yarn install)

stages:
  - name: ✅ Check code style
  - name: Release
    if: branch = master AND type = push

jobs:
  include:
    - stage: ✅ Check code style
      language: node_js
      node_js: 12
      install:
        - yarn install
        - yarn --cwd template install
      script:
        - yarn type-check
        - yarn --cwd template lint

    - stage: Release
      script: npx semantic-release
