language: node_js

node_js:
  - 12

install:
  - gem install cocoapods
  - yarn install
  - cd template && yarn install

stages:
  - name: Check code style
  - name: Release
    if: branch = master

jobs:
  include:
    - stage: Check code style
      script:
        - yarn type-check
        - cd template && yarn lint

    - stage: Release
      script: npx semantic-release
