version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

defaults: &defaults
  docker:
    - image: circleci/node:10.16
      environment:
        TERM: xterm

jobs:
  prepare:
    <<: *defaults
    steps:
      # Git cache
      - restore_cache:
          keys:
            - v1-source-github-{{ .Branch }}-{{ .Revision }}
            - v1-source-github-{{ .Branch }}-
            - v1-source-github-
      - checkout
      - save_cache:
          key: v1-source-github-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      # Yarn cache
      - restore_cache:
          keys:
            - v1-deps-yarn-{{ checksum "package.json" }}
            - v1-deps-yarn-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-yarn-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint project
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test project
          command: yarn test

  coverage:
    <<: *defaults
    environment:
      CC_TEST_REPORTER_ID: 7d932d7d5f674a14f59b06eb4dee56ce2513ec86180b5f8ef53e2308769ca21f
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-cc-test-reporter-0.7.0
      - run:
          name: Download CodeClimate
          command: |
            if [[ ! -x cc-test-reporter ]]
            then
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
            fi
      - save_cache:
          key: v1-cc-test-reporter-0.7.0
          paths:
            - "./cc-test-reporter"
      - run:
          name: Run coverage and upload to Codecov.io
          command: |
            # notify Code Climate of a pending test report using `before-build`
            ./cc-test-reporter before-build
            CI=true yarn coverage
      - run:
          name: "Upload coverage to CodeClimate"
          command: ./cc-test-reporter after-build -t lcov coverage/lcov.info --exit-code $? || true
      - codecov/upload:
          file: coverage/*.json

  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Release a version to NPM and Github
          command: npx semantic-release

workflows:
  version: 2
  build-deps-and-test:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - coverage:
          requires:
            - prepare
      - release:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only:
                - master
